version: "3.7"
services:
  postgres:
    image: postgres:12-alpine
    shm_size: 64M
    ports:
      - "5401:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "4480:80"
  #   volumes:
  #     - ./.data/pgadmin/:/var/lib/pgadmin
